version: 2.1

jobs:
  install-dependencies-39:
    working_directory: ~/dash_mui
    docker:
      - image: cimg/python:3.9.9-node
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PYLINTRC: .pylintrc39
          PYVERSION: python39
          PERCY_ENABLE: 0
      
    steps:
      - checkout
      - run: echo $PYVERSION > ver.txt
      - run: cat requires-*.txt > requires-all.txt
      - restore_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-all.txt" }}
      - run:
          name: Build Component Packages & Update Dependencies/Artifacts
          command: |
            python -m venv venv && . venv/bin/activate
            pip install --upgrade pip wheel
            set -eo pipefail
            pip install -e .[ci,dev,testing] --progress-bar off
            pip list | grep dash_mui
            npm ci
            npm run build
            python setup.py sdist
            mkdir dash-package && cp dist/*.tar.gz dash-package/dash-package.tar.gz
            ls -la dash-package
          no_output_timeout: 30m
      - run:
          name: Display npm errors and exit on failed builds
          command: |
            if [ -d "/home/circleci/.npm/_logs" ]
            then
              cat /home/circleci/.npm/_logs/*
              exit 1
            fi
      - save_cache:
          key: dep-{{ checksum ".circleci/config.yml" }}-{{ checksum "ver.txt" }}-{{ checksum "requires-all.txt" }}
          paths:
            - venv
      - persist_to_workspace:
          root: ~/dash_mui
          paths:
            - dash-package

workflows:
  version: 2
  tests:
    jobs:
      - install-dependencies-39